import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Toolbar from "@/components/ui/toolbar";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html 
      lang="en"
      className="w-full h-full"
    >
      <body
        className={`${inter.variable} antialiased w-full h-full flex flex-col`}
      >
        <Toolbar/>
        {children}
      </body>
    </html>
  );
}
